name: Continuos deploy - CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fazendo rsync dos dados
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-avzhr --progress --delete --exclude adm --exclude staging'
          SOURCE: 'api'
          REMOTE_HOST: forest.orango.io
          REMOTE_USER: root
          REMOTE_PORT: 22
          TARGET: /var/www/filipelopes.me/api
